steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-east4-docker.pkg.dev/arjit-devops/tevio-sample/dev-react:latest", "."]
  
  # 2. Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-east4-docker.pkg.dev/arjit-devops/tevio-sample/dev-react:latest"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "dev-react-service"
      - "--image"
      - "us-east4-docker.pkg.dev/arjit-devops/tevio-sample/dev-react:latest"
      - "--region"
      - "us-east4"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

# Fix the Cloud Build error by specifying logging options
options:
  logging: CLOUD_LOGGING_ONLY  # Store logs in Cloud Logging

timeout: "1200s"  # Increase timeout if needed
